version: '2'
services:
  web:
    restart: always
    image: odoo:8.0
    networks:
      - pg
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./data/addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    container_name: db
    networks:
      - pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  odoo-web-data:

networks:
  pg:

